### ISSUE TITLE
Energy Dashboard - Broken in HA 2022.4 - state class not supported

### ISSUE THREAD

**Issue by shortbloke** [custom-components/sensor.owlintuition#21]
Since updating to 2022.4 (currently on 2022.4.2 - 11 April 2022) the Solar Generating and Exporting data no longer appears to work with the Energy Dashboard. The data is still available as a sensor, but not one that the Energy dashboard can use. The statistics panel reports that they state_class isn't supported:
![image](https://user-images.githubusercontent.com/13274408/162743471-6085cfcd-5eaa-488c-ad80-03d9b6c1cd75.png)

The entity `sensor.owl_intuition_solar_exported_today` has the following attributes:
```
unit_of_measurement: kWh
icon: mdi:flash
friendly_name: Solar Exported Today
```

There isn't a state class attribute `state_class: total_increasing` 
My Electricity consumption figures continue to work as they are using my template sensors which set the state_class.

Looking at the breaking changes in the release, I can't determine which of these is the likely cause of this regression.

Workaround, using template sensor for all sensors used in the Energy Dashboard:
```yaml
####################################################
# Owl Intution - Energy Sensor                     #
####################################################
template:
  - trigger:
    - platform: state
      entity_id: sensor.owl_intuition_electricity_power
    sensor:
      - name: "Owl Grid Energy Now"
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        state: >
          {% if is_state('sensor.owl_intuition_electricity_power', 'unknown') or is_state('sensor.owl_intuition_solar_generating', 'unknown') %}
            nan
          {% else %}
            {% set elec = states('sensor.owl_intuition_electricity_power') | float %}
            {% set solar = states('sensor.owl_intuition_solar_generating') | float %}
            {% if (float(elec) - float(solar)) < 0 %}
              0
            {% elif (float(elec) - float(solar)) > 0 %}
              {{ float(elec) - float(solar) }}
            {% endif %}
          {% endif %}

  - trigger: 
    - platform: state
      entity_id: sensor.owl_intuition_electricity_today
    sensor:
      - name: "Owl Grid Energy Today"
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        state: >
          {% if is_state('sensor.owl_intuition_electricity_today', 'unknown') or is_state('sensor.owl_intuition_solar_generated_today', 'unknown') %}
            nan
          {% else %}
            {% set elec = states('sensor.owl_intuition_electricity_today') | float %}
            {% set solar = states('sensor.owl_intuition_solar_generated_today') | float %}
            {% set last_grid_today = states('sensor.owl_grid_energy_today') | float %}
            {% if (float(elec) - float(solar)) >= 0 %}
              {% if ((float(elec) - float(solar)) > float(last_grid_today)) or ((float(elec) - float(solar)) < 1 ) %}
                {{ float(elec) - float(solar) }}
              {% else %}
                {{ float(last_grid_today) }}
              {% endif %}
            {% endif %}
          {% endif %}

# Workaround - Breaking change in 2022.4
  - trigger: 
    - platform: state
      entity_id: sensor.owl_intuition_solar_exported_today
    sensor:
      - name: "Owl Solar Exported Today (template)"
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        state: >
          {% if is_state('sensor.owl_intuition_solar_exported_today', 'unknown') %}
            nan
          {% else %}
            {{ states('sensor.owl_intuition_solar_exported_today') | float }}
          {% endif %}

  - trigger: 
    - platform: state
      entity_id: sensor.owl_intuition_solar_generated_today
    sensor:
      - name: "Owl Solar Generated Today (template)"
        unit_of_measurement: "kWh"
        state_class: total_increasing
        device_class: energy
        state: >
          {% if is_state('sensor.owl_intuition_solar_generated_today', 'unknown') %}
            nan
          {% else %}
            {{ states('sensor.owl_intuition_solar_generated_today') | float }}
          {% endif %}
```

Resulting entity properties (example):
```
state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
friendly_name: Owl Solar Generated Today (template)
```
