### ISSUE TITLE
Problem in Configuring 

### ISSUE THREAD

**Issue by 03397** [custom-components/sensor.owlintuition#3]
Can you please help in configuring the owl for Home Assistant?
Do I need to enable the Setup Data Push through the dashboard to send the data?  

sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - humidity
  - platform: owlintuition
    port: 4321

**Comment by jchasey** [comment]
Yes you will need to login to your owlintuition dashboard, select Settings from the top menu, then then 'Setup Push Data' in the Advanced Settings section.
The IP address should be the machine you have Home Assistant running on and port number should match the above.
Worth making a note of the UDP key too, more functionality can be accessed with that, although that is not currently supported right now by the sensor, but I'm looking into it...

**Comment by 03397** [comment]
Ok I have manage to do that.
But I am getting values only for the electricity. How can I set it to get values for the remaining sensors.
Is there a way to  start the hot water through the  Home Assistant?

**Comment by jchasey** [comment]
Realised the docs need updating...try setup like this:

```
  - platform: owlintuition
    port: 3200
    host: 10.11.10.5          # IP to return results to
    monitored_conditions:
      - electricity
      - heating
      - hot_water
      - relays
```
