### ISSUE TITLE
Is this repo still being updated?

### ISSUE THREAD

**Issue by coleburg** [custom-components/sensor.owlintuition#34]
This hasnt worked for a long time, I think the last HA version this worked with was Aprils.

It would be great to get this working with the latest builds please

**Comment by shortbloke** [comment]
It's still working and has been updated to address breaking changes in HA. 

I'm using:
```
Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest
```
with
```
HACS: 1.33.0
Owl Intuition: 5ea865d
```

**Comment by glpatcern** [comment]
@shortbloke is definitely more up to date with HA, for the time being I'm not able to follow that closely. Yet, I may review/fix code on demand following the (relatively numerous) breaking changes in HA.

**Comment by coleburg** [comment]
> It's still working and has been updated to address breaking changes in HA.
> 
> I'm using:
> 
> ```
> Home Assistant 2023.9.3
> Supervisor 2023.09.2
> Operating System 10.5
> Frontend 20230911.0 - latest
> ```
> 
> with
> 
> ```
> HACS: 1.33.0
> Owl Intuition: 5ea865d
> ```

Ive just moved to the exact build as you but im getting 

Cannot quick reload all YAML configurations because the configuration is not valid: Platform error sensor.owlintuition - Exception importing custom_components.owlintuition.sensor

**Comment by shortbloke** [comment]
@coleburg What's your YAML configuration look like? Mine is:
```
# Owl Energy Monitor
- platform: owlintuition
  host: 192.168.200.45
  port: 32000
  mode: triphase
  cost_icon: 'mdi:currency-gbp'
  cost_unit_of_measurement: GBP
  monitored_conditions:
    - electricity
    - solar
```
